export const financePaths = {
  invoices: "/invoices",
  invoice: (id: string) => `/invoices/${id}`,
  invoiceFromProposal: "/invoices/from-proposal",
  invoiceLineItems: (id: string) => `/invoices/${id}/line-items`,
  sendInvoice: (id: string) => `/invoices/${id}/send`,
  voidInvoice: (id: string) => `/invoices/${id}/void`,
  cancelInvoice: (id: string) => `/invoices/${id}/cancel`,
  remindInvoice: (id: string) => `/invoices/${id}/remind`,
  payments: "/payments",
  payment: (id: string) => `/payments/${id}`,
  refunds: "/refunds",
  creditNotes: "/credit-notes",
  creditNote: (id: string) => `/credit-notes/${id}`,
  expenses: "/expenses",
  expense: (id: string) => `/expenses/${id}`,
  forgeFundEntries: "/forge-fund-entries",
  forgeFundEntry: (id: string) => `/forge-fund-entries/${id}`,
  forgeFundBalance: "/forge-fund/balance",
} as const;
