export const crmPaths = {
  companies: "/companies",
  company: (id: string) => `/companies/${id}`,
  archiveCompany: (id: string) => `/companies/${id}/archive`,
  contacts: "/contacts",
  contact: (id: string) => `/contacts/${id}`,
  archiveContact: (id: string) => `/contacts/${id}/archive`,
  leads: "/leads",
  lead: (id: string) => `/leads/${id}`,
  transitionLead: (id: string) => `/leads/${id}/transition`,
  convertLead: (id: string) => `/leads/${id}/convert`,
  archiveLead: (id: string) => `/leads/${id}/archive`,
  deals: "/deals",
  deal: (id: string) => `/deals/${id}`,
  transitionDeal: (id: string) => `/deals/${id}/transition`,
  reopenDeal: (id: string) => `/deals/${id}/reopen`,
  archiveDeal: (id: string) => `/deals/${id}/archive`,
  bulkReassignDeals: "/deals/bulk-reassign",
  activities: "/activities",
  projects: "/projects",
  forgeFundEntries: "/forge-fund-entries",
  forgeFundBalance: "/forge-fund/balance",
} as const;
