export const earningsPaths = {
  projectAllocations: "/project-allocations",
  projectAllocation: (id: string) => `/project-allocations/${id}`,
  projectAllocationLines: (id: string) => `/project-allocations/${id}/lines`,
  approveProjectAllocation: (id: string) => `/project-allocations/${id}/approve`,
  cancelProjectAllocation: (id: string) => `/project-allocations/${id}/cancel`,
  adjustProjectAllocation: (id: string) => `/project-allocations/${id}/adjust`,
  payouts: "/payouts",
  payout: (id: string) => `/payouts/${id}`,
  reviewPayout: (id: string) => `/payouts/${id}/review`,
  approvePayout: (id: string) => `/payouts/${id}/approve`,
  rejectPayout: (id: string) => `/payouts/${id}/reject`,
  processPayout: (id: string) => `/payouts/${id}/process`,
  markPayoutPaid: (id: string) => `/payouts/${id}/mark-paid`,
  markPayoutFailed: (id: string) => `/payouts/${id}/mark-failed`,
  teamEarnings: "/team/earnings",
  teamEarningsAllocations: "/team/earnings/allocations",
  teamPayouts: "/team/payouts",
  teamPayout: (id: string) => `/team/payouts/${id}`,
} as const;
